version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 10
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test: off
artifacts:
- path: SteamAccCreator\bin\$(configuration)
  name: Release-windows-$(appveyor_build_version)
deploy: off